POST http://localhost:3080/api/v1/login
Content-Type: application/json

{
    "email" : "mouhamadalmounayar@gmail.com",
    "password" : "M2003ouhamed"
}
###
POST http://localhost:3080/api/v1/register/
Content-Type : application/json

{
    "username" : "mouhamad010102030210201",
    "email" : "mouhamad@gmail.com",
    "password" : "M2003ouhamed"
}